import { readdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

// Two artifacts, deliberately: the Presets modal lists the index, which must
// stay small because a preset workflow embeds its sample file as base64.
// Bundling both together made opening the modal download every preset's
// sample, whether or not one was ever picked.
const root = fileURLToPath(new URL('..', import.meta.url));
const manifest = JSON.parse(await readFile(`${root}/manifest.json`, 'utf8'));

await writeFile(`${root}/preset-index.json`, `${JSON.stringify(manifest, null, 2)}\n`);

// A static map of dynamic imports, so the bundler gives each workflow its own
// chunk. A computed `import(path)` would defeat that.
const entries = manifest
  .map((entry) => `  ${JSON.stringify(entry.file)}: () => import('./presets/${entry.file}'),`)
  .join('\n');

await writeFile(
  `${root}/preset-loaders.js`,
  `// Generated by scripts/build-presets.mjs. Do not edit.\nexport const PRESET_LOADERS = {\n${entries}\n};\n`,
);

console.log(`build-presets: indexed ${manifest.length} presets, wrote preset-index.json and preset-loaders.js`);

// Samples split like presets do: a file field's Sample tab only needs names to
// draw its list, and one 3MB WAV should not ride along because someone opened
// a picker.
const sampleNames = (await readdir(`${root}/samples`)).filter((f) => f.endsWith('.json')).sort();
const index = [];
const loaders = [];
for (const jsonName of sampleNames) {
  const sample = JSON.parse(await readFile(`${root}/samples/${jsonName}`, 'utf8'));
  index.push({ name: sample.name, mime: sample.dataUrl.slice(5, sample.dataUrl.indexOf(';')) });
  loaders.push(`  ${JSON.stringify(sample.name)}: () => import('./samples/${jsonName}'),`);
}

await writeFile(`${root}/sample-index.json`, `${JSON.stringify(index, null, 2)}\n`);
await writeFile(
  `${root}/sample-loaders.js`,
  `// Generated by scripts/build-presets.mjs. Do not edit.\nexport const SAMPLE_LOADERS = {\n${loaders.join('\n')}\n};\n`,
);

console.log(`build-presets: indexed ${index.length} samples, wrote sample-index.json and sample-loaders.js`);
